name: tsh_soft
description: "A comprehensive e-commerce platform delivering seamless shopping experiences, with smart content management and contemporary design that caters to both customers and merchants."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  intl: ^0.19.0
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  dartz: ^0.10.1
  connectivity_plus: ^6.1.1
  go_router: ^14.6.2
  get_it: ^8.0.3
  injectable: ^2.5.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  package_info_plus: ^8.1.2
  flutter_svg: ^2.0.16
  video_player: ^2.9.2
  cached_network_image: ^3.4.1
  icons_plus: ^5.0.0
  skeletonizer: ^1.4.2
  another_stepper: ^1.2.2
  auto_size_text: ^3.0.0
  badges: ^3.1.2
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.3
  carousel_slider: ^5.0.0
  circular_menu: ^4.0.0
  collection: ^1.18.0
  country_picker: ^2.0.20
  dotted_line: ^3.2.2
  easy_stepper: ^0.8.5
  fl_chart: ^0.69.0
 
  flutter_html: ^3.0.0-alpha.3
  flutter_local_notifications: ^17.1.0
  flutter_otp_text_field: ^1.1.3+2
  flutter_riverpod: ^2.4.9
  flutter_secure_storage: ^9.0.0
  font_awesome_flutter: ^10.5.0
  geocoding: ^3.0.0
  geolocator: ^13.0.1
  google_maps_flutter: ^2.5.0
  google_nav_bar: ^5.0.6
  http: ^1.2.1
  image_picker: ^1.0.4
  internet_connection_checker_plus: ^2.1.0
  loading_animation_widget: ^1.2.1
  logger: ^2.0.1
  lottie: ^3.0.0
  percent_indicator: ^4.2.3
  phone_number: ^2.0.1
  photo_view: ^0.15.0
  pin_code_text_field: ^1.8.0
  rename: ^3.0.2
  shared_preferences: ^2.2.0
  shimmer: ^3.0.0
  stream_transform: ^2.1.0
  url_launcher: ^6.2.1
  device_preview: 
  

  ## IOS
  permission_handler: ^11.3.1
  firebase_messaging: ^15.1.3
  firebase_core: ^3.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  go_router_builder: ^2.7.1
  injectable_generator: ^2.6.2
  build_runner: ^2.4.13

flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/
    - lang/ar.json
    - lang/en.json
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/anim/

  fonts:
    - family: ElMessiri
      fonts:
        - asset: assets/fonts/ElMessiri/ElMessiri-Bold.ttf
          weight: 700
        - asset: assets/fonts/ElMessiri/ElMessiri-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ElMessiri/ElMessiri-Medium.ttf
          weight: 500
        - asset: assets/fonts/ElMessiri/ElMessiri-Regular.ttf
          weight: 400